// Run the scenario-converted unit tests (generated by tools/convert-tests.js
// from test/{map,filter,flatMap}.js) against the real implementations. These
// encode the same stimuli and expected logs as the originals, so they must
// all pass; a failure here means the converter or the scenario executors
// drifted from the hand-written suite.

import { map } from '../map.js';
import { filter } from '../filter.js';
import { flatMap } from '../flatMap.ts';
import * as utils from './utils.js';
import { scenarioTest } from '../../async-iterator-animations/scenarios/scenario-to-test.js';
import { mapTestScenarios } from '../../async-iterator-animations/scenarios/map-test-scenarios.js';
import { filterTestScenarios } from '../../async-iterator-animations/scenarios/filter-test-scenarios.js';
import { flatMapTestScenarios } from '../../async-iterator-animations/scenarios/flatmap-test-scenarios.js';

const helpers = { map, filter, flatMap };
const all = [...mapTestScenarios, ...filterTestScenarios, ...flatMapTestScenarios];

await utils.runTests(all.map((s) => scenarioTest(s, { helper: helpers[s.helper], utils })));
